### ISSUE TITLE
can you make item name's clear _

### ISSUE THREAD

**Issue by hemato** [felipelincoln/albion-blackmarket-tool#3]
i cant find item names when i look images. how to fix this ?

**Comment by hemato** [comment]
@felipelincoln  why v4 is not suported windows :D

**Comment by felipelincoln** [comment]
> @felipelincoln why v4 is not suported windows :D

you were faster than me :smile: see again and it will be there. [v0.4](https://github.com/felipelincoln/albion-blackmarket-tool/releases/tag/v0.4)

It looks this way now.
![](https://raw.githubusercontent.com/felipelincoln/albion-blackmarket-tool/master/img/screenshot.png)

If you have any otther request or problem feel free to open another issue.

**Comment by hemato** [comment]
and i almost checked 10 items and none of them matches with in game prices. :S
