### ISSUE TITLE
virüstotal

### ISSUE THREAD

**Issue by hemato** [felipelincoln/albion-blackmarket-tool#4]
https://www.virustotal.com/gui/file/6eb34b307b1bb99c49db163373777de32ce91393cd1889cac35d66932024f438/detection

https://prnt.sc/s7lzf2

what is this bro :S

**Comment by felipelincoln** [comment]
I don't really know what these engines are :thinking:, did previous versions not reported it?

**Comment by hemato** [comment]
i checked previous version too when i check new one it is ;
https://www.virustotal.com/gui/file/aa1e956a0893fd5d89baf2f0456f29adbbf1488c29847b3414e726e1995e897a/detection

**Comment by felipelincoln** [comment]
Well, I gotta take a closer look at these. If you are not comfortable running this executable on your windows you can generate the executable file yourself. Clone this repository and:
```
pip install pipenv
pipenv install --system
pipenv shell
pyinstaller main.py
```

go to creted `dist` folder and find the `main.exe` file there.

**Comment by felipelincoln** [comment]
I just took a time to investigate it and it seems that `pyinstaller` may raise false positive trojan indicator for some anti-virus, this is not a problem with this program and neither with `pyinstaller` but with the anti-virus. See this [Trojan after compiling #4852](https://github.com/pyinstaller/pyinstaller/issues/4852).  
There is not I can do about it so I am closing this issue. :blush:

**Comment by felipelincoln** [comment]
I just took a time to investigate it and it seems that `pyinstaller` may raise false positive trojan indicator for some anti-virus, this is not a problem with this program and neither with `pyinstaller` but with the anti-virus. See this [Trojan after compiling #4852](https://github.com/pyinstaller/pyinstaller/issues/4852).  
There is not I can do about it so I am closing this issue. :blush:
